/* test.c generated by valac 0.36.1.47-a667b, the Vala compiler
 * generated from test.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdio.h>


#define TYPE_MY_LIB (my_lib_get_type ())
#define MY_LIB(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_MY_LIB, MyLib))
#define MY_LIB_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_MY_LIB, MyLibClass))
#define IS_MY_LIB(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_MY_LIB))
#define IS_MY_LIB_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_MY_LIB))
#define MY_LIB_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_MY_LIB, MyLibClass))

typedef struct _MyLib MyLib;
typedef struct _MyLibClass MyLibClass;
typedef struct _MyLibPrivate MyLibPrivate;
enum  {
	MY_LIB_DUMMY_PROPERTY,
	MY_LIB_LAST_PROPERTY
};
static GParamSpec* my_lib_properties[MY_LIB_LAST_PROPERTY];

struct _MyLib {
	GObject parent_instance;
	MyLibPrivate * priv;
};

struct _MyLibClass {
	GObjectClass parent_class;
};


static gpointer my_lib_parent_class = NULL;

GType my_lib_get_type (void) G_GNUC_CONST;
void my_lib_hello (MyLib* self);
gint my_lib_sum (MyLib* self, gint x, gint y);
MyLib* my_lib_new (void);
MyLib* my_lib_construct (GType object_type);


void my_lib_hello (MyLib* self) {
	FILE* _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = stdout;
	fprintf (_tmp0_, "Hello World, MyLib\n");
}


gint my_lib_sum (MyLib* self, gint x, gint y) {
	gint result = 0;
	gint _tmp0_;
	gint _tmp1_;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = x;
	_tmp1_ = y;
	result = _tmp0_ + _tmp1_;
	return result;
}


MyLib* my_lib_construct (GType object_type) {
	MyLib * self = NULL;
	self = (MyLib*) g_object_new (object_type, NULL);
	return self;
}


MyLib* my_lib_new (void) {
	return my_lib_construct (TYPE_MY_LIB);
}


static void my_lib_class_init (MyLibClass * klass) {
	my_lib_parent_class = g_type_class_peek_parent (klass);
}


static void my_lib_instance_init (MyLib * self) {
}


GType my_lib_get_type (void) {
	static volatile gsize my_lib_type_id__volatile = 0;
	if (g_once_init_enter (&my_lib_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (MyLibClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) my_lib_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (MyLib), 0, (GInstanceInitFunc) my_lib_instance_init, NULL };
		GType my_lib_type_id;
		my_lib_type_id = g_type_register_static (G_TYPE_OBJECT, "MyLib", &g_define_type_info, 0);
		g_once_init_leave (&my_lib_type_id__volatile, my_lib_type_id);
	}
	return my_lib_type_id__volatile;
}



