/* test.h generated by valac 0.30.1, the Vala compiler, do not modify */


#ifndef __TEST_H__
#define __TEST_H__

#include <glib.h>
#include <glib-object.h>

G_BEGIN_DECLS


#define TYPE_MY_LIB (my_lib_get_type ())
#define MY_LIB(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_MY_LIB, MyLib))
#define MY_LIB_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_MY_LIB, MyLibClass))
#define IS_MY_LIB(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_MY_LIB))
#define IS_MY_LIB_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_MY_LIB))
#define MY_LIB_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_MY_LIB, MyLibClass))

typedef struct _MyLib MyLib;
typedef struct _MyLibClass MyLibClass;
typedef struct _MyLibPrivate MyLibPrivate;

struct _MyLib {
	GObject parent_instance;
	MyLibPrivate * priv;
};

struct _MyLibClass {
	GObjectClass parent_class;
};


GType my_lib_get_type (void) G_GNUC_CONST;
void my_lib_hello (MyLib* self);
gint my_lib_sum (MyLib* self, gint x, gint y);
MyLib* my_lib_new (void);
MyLib* my_lib_construct (GType object_type);


G_END_DECLS

#endif
